# Decommissioned on 2020/04/11. Now using GitHub Actions
trigger: none
  #branches:
    #include:
    #- master

variables:
    buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: "Build and Push to Stage"
  jobs:
  - job: Build
    displayName: Build job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    # Install all npm package dependencies for the angular web client
    - script: npm ci
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      displayName: 'Install npm packages dependencies'

    # Build the angular web client
    - script: npx ng build --prod
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      displayName: 'Build WebClient'

    # Find the newly created dist folder with web client artifacts zip them to artifacts staging for release pipeline
    - task: ArchiveFiles@2
      displayName: 'Zip WebClient Artifacts'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/webclient.zip'

    # Publish build artifacts
    # Should have:
    # webapi.zip
    # webclient.zip
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts'        

- stage: Release
  displayName: "Push to Production"
  jobs:
  - deployment: DeployGrenitausConsulting
    pool:
      vmImage: 'ubuntu-latest'
    environment: prod
    strategy:
      runOnce:
        deploy:
          steps:
          # Publish build artifacts
          # Should have:
          # webclient.zip
          # Deploy Angular Web Client
          - task: AzureRMWebAppDeployment@4
            displayName: 'Deploy Web Client'
            inputs:
              WebAppKind: webApp
              ConnectedServiceName: 'sc_arm_websites'
              WebAppName: $(azure.webapp.webclient.name)
              Package: $(System.WorkFolder)/**/webclient.zip